package com.oai.geminilivetranslate.ui

object AiStudioWebSessionR18RuntimeBootstrap {
    const val VERSION = "2026-09-04-r18.8-lineage-callback-warm-replay-r18.9-cold-reload-bootstrap"
    const val TARGET_MODEL = "gemini-3.5-live-translate-preview"

    val DOCUMENT_START: String = """
(function(){
  'use strict';
  if(window.__AIS_R183B_BOOTSTRAP__&&window.__AIS_R183B_BOOTSTRAP__.version)return;
  const VERSION='2026-09-04-r18.8-lineage-callback-warm-replay-r18.9-cold-reload-bootstrap';
  const TARGET_MODEL='gemini-3.5-live-translate-preview';
  const FP_KEY='__AIS_R189_COLD_FP__';
  const FP_TTL_MS=15*60*1000,MAX_CONTEXTS=900,MAX_LINEAGE=48,MAX_CANDIDATES=32;
  const nativeSetTimeout=window.setTimeout.bind(window),nativeClearTimeout=window.clearTimeout.bind(window);
  function bridge(kind,payload){try{const b=window.AIStudioWebSessionLab;if(b&&typeof b.onJsEvent==='function')b.onJsEvent(JSON.stringify({kind:'R183B_'+kind,payload:payload||{}}));}catch(_){}}
  function hashText(v){let h=2166136261,s=String(v||'');for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619);}return (h>>>0).toString(16);}
  function fnSource(fn){try{return Function.prototype.toString.call(fn);}catch(_){return '';}}
  function typeName(v){try{return v&&v.constructor&&v.constructor.name||typeof v;}catch(_){return typeof v;}}
  function safeCode(v){const s=String(v||'vi').trim().slice(0,32);return /^[A-Za-z0-9-]+$/.test(s)?s:'vi';}
  function callable(listener){if(typeof listener==='function')return listener;try{if(listener&&typeof listener.handleEvent==='function')return listener.handleEvent;}catch(_){}return null;}
  function isUiObject(v){try{if(v===window||v===document)return true;}catch(_){}try{if(typeof Node==='function'&&v instanceof Node)return true;}catch(_){}return false;}
  function isUiArg(v){try{if(typeof Event==='function'&&v instanceof Event)return true;}catch(_){}return isUiObject(v);}
  function contextMeta(c){return c?{id:c.id,parentId:c.parentId,rootId:c.rootId,kind:c.kind,depth:c.depth,runCount:c.runCount||0,callbackHash:c.callbackHash||'',callbackArity:c.callbackArity,callbackArgTypes:(c.callbackArgTypes||[]).slice(0,8),callbackHasUiArg:!!c.callbackHasUiArg}:null;}
  function readFp(){try{const raw=sessionStorage.getItem(FP_KEY);if(!raw)return null;sessionStorage.removeItem(FP_KEY);const x=JSON.parse(raw),age=Date.now()-Number(x&&x.ts||0),hash=String(x&&x.hash||''),kind=String(x&&x.kind||''),arity=Number(x&&x.arity);if(age<0||age>FP_TTL_MS||!/^[0-9a-f]{4,16}$/i.test(hash)||!Number.isInteger(arity)||arity<0||arity>8)return null;if(!/^(promise-fulfill|promise-reject|promise-catch|promise-finally|queueMicrotask|scheduler\.postTask|requestAnimationFrame|setTimeout|setInterval)$/.test(kind))return null;return {hash:hash,arity:arity,kind:kind,ageMs:age};}catch(_){try{sessionStorage.removeItem(FP_KEY);}catch(__){}return null;}}
  const bootFingerprint=readFp(),coldMode=!!bootFingerprint;
  const state={configured:false,armed:true,targetLanguage:'vi',mode:coldMode?'cold-reload':'learn-warm',stage:coldMode?'cold-awaiting-fingerprint':'idle',lastError:'',listenerRoots:0,asyncScheduled:0,asyncRuns:0,contextDrops:0,bidiRequests:0,setupObservations:0,setupLinked:0,setupUnlinked:0,lineageDepth:0,callbackCandidateCount:0,safeCallbackCandidateCount:0,callbackTop:[],selected:null,replayScheduled:false,callbackReplayAttempts:0,callbackReplayReturns:0,callbackReplayPromises:0,callbackReplayErrors:0,callbackReplaySetupSendDelta:0,callbackReplayBidiDelta:0,callbackReplayOutcome:'not-run',warmOnly:!coldMode,persistedFingerprint:null,coldFingerprint:bootFingerprint,coldCallbacksObserved:0,coldMatchCount:0,coldMatch:null,coldReplayScheduled:false,coldReplayAttempts:0,coldReplayReturns:0,coldReplayPromises:0,coldReplayErrors:0,coldSetupSendDelta:0,coldBidiDelta:0,coldR16SetupDelta:0,coldLanguageVerified:false,coldSyntheticCarrier:false,coldSyntheticErrors:0,coldOutcome:coldMode?'cold-waiting':'not-cold-phase',coldNetworkSetupProven:false,coldBootstrapProven:false,lastRoot:null,firstSetup:null,lastSetup:null,lastRequestProfile:null};
  let currentContext=null,nextContextId=1,replayTimer=null,replayEvalTimer=null,coldReplayTimer=null,coldEvalTimer=null;
  const contexts=[],contextById=new Map(),callbackCandidates=[],coldMatches=[];
  function makeContext(kind,parent,fn){if(contexts.length>=MAX_CONTEXTS){state.contextDrops++;return parent||null;}const id=nextContextId++,c={id:id,parentId:parent?parent.id:0,rootId:parent?parent.rootId:id,kind:String(kind||'async').slice(0,64),depth:parent?parent.depth+1:0,runCount:0,fn:typeof fn==='function'?fn:null,callbackHash:typeof fn==='function'?hashText(fnSource(fn)):'',callbackArity:typeof fn==='function'?Number(fn.length||0):-1,callbackArgs:[],callbackArgTypes:[],callbackHasUiArg:false};contexts.push(c);contextById.set(id,c);if(parent)state.asyncScheduled++;return c;}
  function runContext(c,fn,self,args){if(typeof fn!=='function')return;const prev=currentContext;currentContext=c;if(c){c.runCount++;state.asyncRuns++;const a=(args||[]).slice(0,8);c.callbackArgs=a;c.callbackArgTypes=a.map(typeName);c.callbackHasUiArg=a.some(isUiArg);}try{return fn.apply(self,args||[]);}finally{currentContext=prev;}}
  function chainFor(c){const out=[],seen=new Set();while(c&&out.length<MAX_LINEAGE&&!seen.has(c.id)){seen.add(c.id);out.push(c);c=c.parentId?contextById.get(c.parentId):null;}return out.reverse();}
  function isSafeCallback(c){if(!c||typeof c.fn!=='function'||c.kind==='exact-click-root'||c.runCount<1||c.callbackHasUiArg)return false;if(c.callbackArity===0)return true;return c.callbackArgs.length>=c.callbackArity&&c.callbackArgs.length<=8;}
  function analyzeLineage(setupCtx){callbackCandidates.length=0;const chain=chainFor(setupCtx),sd=setupCtx?setupCtx.depth:0;state.lineageDepth=chain.length;for(let i=0;i<chain.length;i++){const c=chain[i];if(typeof c.fn!=='function'||c.kind==='exact-click-root')continue;const safe=isSafeCallback(c),dist=Math.max(0,sd-c.depth),score=220-Math.min(160,dist*24)+(c.kind.indexOf('promise')===0?18:0)+(c.callbackArity===0?30:0)+(c.runCount>0?10:0);callbackCandidates.push({ctx:c,fn:c.fn,args:c.callbackArgs.slice(0,8),safe:safe,score:score,meta:{contextId:c.id,contextDepth:c.depth,distanceFromSetup:dist,contextKind:c.kind,callbackHash:c.callbackHash,callbackArity:c.callbackArity,callbackArgTypes:c.callbackArgTypes.slice(0,8),callbackHasUiArg:c.callbackHasUiArg,runCount:c.runCount,safe:safe,score:score}});}callbackCandidates.sort((a,b)=>a.safe!==b.safe?(a.safe?-1:1):a.meta.distanceFromSetup!==b.meta.distanceFromSetup?a.meta.distanceFromSetup-b.meta.distanceFromSetup:a.meta.callbackArity-b.meta.callbackArity||b.score-a.score);if(callbackCandidates.length>MAX_CANDIDATES)callbackCandidates.splice(MAX_CANDIDATES);state.callbackCandidateCount=callbackCandidates.length;const safe=callbackCandidates.filter(c=>c.safe);state.safeCallbackCandidateCount=safe.length;state.callbackTop=callbackCandidates.slice(0,12).map(c=>c.meta);if(safe.length){const best=safe[0],second=safe[1];state.selected=Object.assign({},best.meta,{selectionMargin:second?best.score-second.score:999,warmOnly:true});try{const fp={hash:best.meta.callbackHash,arity:best.meta.callbackArity,kind:best.meta.contextKind,ts:Date.now(),model:TARGET_MODEL};sessionStorage.setItem(FP_KEY,JSON.stringify(fp));state.persistedFingerprint={hash:fp.hash,arity:fp.arity,kind:fp.kind,ts:fp.ts};bridge('R189_FINGERPRINT_PERSISTED',state.persistedFingerprint);}catch(e){bridge('R189_FINGERPRINT_STORE_ERROR',{name:String(e&&e.name||'Error')});}}else state.selected=null;return chain;}
  function selectedCandidate(){if(!state.selected)return null;return callbackCandidates.find(c=>c.meta.contextId===state.selected.contextId)||null;}
  function scheduleWarmReplay(){if(coldMode||state.replayScheduled||state.callbackReplayAttempts>0)return;const c=selectedCandidate();if(!c||!c.safe){state.callbackReplayOutcome='no-safe-callback';return;}state.replayScheduled=true;state.stage='warm-replay-scheduled';replayTimer=nativeSetTimeout(runWarmReplay,1800);}
  function runWarmReplay(){state.replayScheduled=false;const c=selectedCandidate();if(!c||!c.safe){state.callbackReplayOutcome='candidate-lost';return;}const bs=state.setupObservations,bb=state.bidiRequests;state.callbackReplayAttempts++;state.stage='warm-replay-running';const replayCtx=makeContext('warm-callback-replay-root',null,c.fn);try{const args=c.meta.callbackArity===0?[]:c.args.slice(0,c.meta.callbackArity);const ret=runContext(replayCtx,c.fn,undefined,args);state.callbackReplayReturns++;if(ret&&typeof ret.then==='function'){state.callbackReplayPromises++;try{ret.catch(()=>state.callbackReplayErrors++);}catch(_){}}}catch(e){state.callbackReplayErrors++;state.lastError=String(e&&e.name||'Error');}replayEvalTimer=nativeSetTimeout(function(){state.callbackReplaySetupSendDelta=Math.max(0,state.setupObservations-bs);state.callbackReplayBidiDelta=Math.max(0,state.bidiRequests-bb);state.callbackReplayOutcome=state.callbackReplaySetupSendDelta>0?'warm-setup-replayed':state.callbackReplayBidiDelta>0?'warm-bidi-activity':state.callbackReplayErrors>0?'warm-replay-error':'warm-no-network-delta';state.stage='warm-replay-complete';bridge('R188_WARM_REPLAY_RESULT',{selected:state.selected,callbackReplaySetupSendDelta:state.callbackReplaySetupSendDelta,callbackReplayBidiDelta:state.callbackReplayBidiDelta,callbackReplayErrors:state.callbackReplayErrors,callbackReplayOutcome:state.callbackReplayOutcome,warmOnly:true,coldBootstrapProven:false});},1200);}
  function observeCold(fn,kind){if(!coldMode||!bootFingerprint||typeof fn!=='function'||state.coldReplayAttempts>0)return;state.coldCallbacksObserved++;const arity=Number(fn.length||0);if(arity!==bootFingerprint.arity||String(kind)!==bootFingerprint.kind)return;const h=hashText(fnSource(fn));if(h!==bootFingerprint.hash)return;if(!coldMatches.some(x=>x.fn===fn))coldMatches.push({fn:fn,hash:h,arity:arity,kind:String(kind)});state.coldMatchCount=coldMatches.length;state.coldMatch={hash:h,arity:arity,kind:String(kind),uniqueCount:coldMatches.length};state.stage=coldMatches.length===1?'cold-callback-seen':'cold-ambiguous-fingerprint';bridge('R189_COLD_CALLBACK_MATCH',state.coldMatch);if(coldMatches.length===1&&!state.coldReplayScheduled){state.coldReplayScheduled=true;coldReplayTimer=nativeSetTimeout(runColdReplayIfUnique,900);}}
  function runColdReplayIfUnique(){state.coldReplayScheduled=false;if(!coldMode||state.coldReplayAttempts>0)return;if(coldMatches.length!==1){state.coldOutcome='cold-ambiguous-fingerprint';state.stage='cold-failed-ambiguous';return;}const c=coldMatches[0];if(c.arity!==0){state.coldOutcome='cold-match-unsafe-arity';state.stage='cold-failed-arity';return;}try{const g=window.__AIS_R183_LANGUAGE__;if(g&&typeof g.configure==='function')g.configure('vi');}catch(_){}const bs=state.setupObservations,bb=state.bidiRequests;let br=0;try{const o=window.__AIS_LIVE_OUTPUT_ENGINE__&&window.__AIS_LIVE_OUTPUT_ENGINE__.describe();br=Number(o&&o.setupCompleteEvents||0);}catch(_){}state.coldReplayAttempts++;state.stage='cold-replay-running';state.coldOutcome='cold-replay-running';const rc=makeContext('cold-callback-replay-root',null,c.fn);try{const ret=runContext(rc,c.fn,undefined,[]);state.coldReplayReturns++;if(ret&&typeof ret.then==='function'){state.coldReplayPromises++;try{ret.catch(()=>state.coldReplayErrors++);}catch(_){}}}catch(e){state.coldReplayErrors++;state.lastError=String(e&&e.name||'Error');}coldEvalTimer=nativeSetTimeout(function(){state.coldSetupSendDelta=Math.max(0,state.setupObservations-bs);state.coldBidiDelta=Math.max(0,state.bidiRequests-bb);let ar=br;try{const o=window.__AIS_LIVE_OUTPUT_ENGINE__&&window.__AIS_LIVE_OUTPUT_ENGINE__.describe();ar=Number(o&&o.setupCompleteEvents||0);}catch(_){}state.coldR16SetupDelta=Math.max(0,ar-br);try{const g=window.__AIS_R183_LANGUAGE__&&window.__AIS_R183_LANGUAGE__.describe();state.coldLanguageVerified=!!(g&&g.targetLanguageVerified);}catch(_){}state.coldNetworkSetupProven=state.coldSetupSendDelta>0;state.coldBootstrapProven=state.coldSetupSendDelta>0&&state.coldR16SetupDelta>0&&state.coldLanguageVerified;state.coldOutcome=state.coldBootstrapProven?'cold-bootstrap-confirmed':state.coldSetupSendDelta>0?'cold-network-setup-only':state.coldBidiDelta>0?'cold-bidi-activity':state.coldReplayErrors>0?'cold-replay-error':'cold-no-network-delta';state.stage='cold-replay-complete';bridge('R189_COLD_REPLAY_RESULT',{fingerprint:bootFingerprint,coldMatchCount:state.coldMatchCount,coldSetupSendDelta:state.coldSetupSendDelta,coldBidiDelta:state.coldBidiDelta,coldR16SetupDelta:state.coldR16SetupDelta,coldLanguageVerified:state.coldLanguageVerified,coldReplayErrors:state.coldReplayErrors,coldOutcome:state.coldOutcome,coldBootstrapProven:state.coldBootstrapProven});},3200);}
  function trackScheduled(fn,kind){observeCold(fn,kind);if(typeof fn!=='function'||!currentContext)return fn;const c=makeContext(kind,currentContext,fn);return function(){return runContext(c,fn,this,Array.prototype.slice.call(arguments));};}
  try{const na=EventTarget.prototype.addEventListener,nr=EventTarget.prototype.removeEventListener,maps=new WeakMap();EventTarget.prototype.addEventListener=function(type,listener,options){const fn=callable(listener);if(String(type||'')!=='click'||!fn)return na.apply(this,arguments);const target=this,wrapped=function(ev){let exact=false;try{exact=!coldMode&&state.armed&&ev&&ev.type==='click'&&ev.isTrusted===false&&target===ev.target&&String(target&&target.tagName||'').toUpperCase()==='BUTTON';}catch(_){}if(!exact){if(typeof listener==='function')return listener.call(this,ev);return listener.handleEvent.call(listener,ev);}const root=makeContext('exact-click-root',null,fn);state.listenerRoots++;state.lastRoot=contextMeta(root);state.stage='oracle-root-observed';return runContext(root,function(){if(typeof listener==='function')return listener.call(target,ev);return listener.handleEvent.call(listener,ev);},null,[]);};let m=maps.get(target);if(!m){m=new WeakMap();maps.set(target,m);}try{m.set(listener,wrapped);}catch(_){}return na.call(target,type,wrapped,options);};EventTarget.prototype.removeEventListener=function(type,listener,options){if(String(type||'')==='click'&&listener){try{const m=maps.get(this),w=m&&m.get(listener);if(w)return nr.call(this,type,w,options);}catch(_){}}return nr.apply(this,arguments);};}catch(e){bridge('R189_HOOK_ERROR',{target:'EventTarget',name:String(e&&e.name||'Error')});}
  try{const nt=Promise.prototype.then;Promise.prototype.then=function(a,b){return nt.call(this,trackScheduled(a,'promise-fulfill'),trackScheduled(b,'promise-reject'));};}catch(e){bridge('R189_HOOK_ERROR',{target:'Promise.then',name:String(e&&e.name||'Error')});}
  try{const nc=Promise.prototype.catch;Promise.prototype.catch=function(a){return nc.call(this,trackScheduled(a,'promise-catch'));};}catch(_){}
  try{const nf=Promise.prototype.finally;if(typeof nf==='function')Promise.prototype.finally=function(a){return nf.call(this,trackScheduled(a,'promise-finally'));};}catch(_){}
  try{const nq=window.queueMicrotask;if(typeof nq==='function')window.queueMicrotask=function(fn){return nq.call(this,trackScheduled(fn,'queueMicrotask'));};}catch(_){}
  try{const ntm=window.setTimeout;window.setTimeout=function(fn,delay){if(typeof fn!=='function')return ntm.apply(this,arguments);const args=Array.prototype.slice.call(arguments,2),w=trackScheduled(fn,'setTimeout');return ntm(function(){return w.apply(this,args);},delay);};}catch(_){}
  try{const ni=window.setInterval;window.setInterval=function(fn,delay){if(typeof fn!=='function')return ni.apply(this,arguments);const args=Array.prototype.slice.call(arguments,2),w=trackScheduled(fn,'setInterval');return ni(function(){return w.apply(this,args);},delay);};}catch(_){}
  // MessageChannel remains an observed async boundary in the historical R18.8 tracer; cold matching is restricted to explicit callback registration APIs.
  try{const nr=window.requestAnimationFrame;if(typeof nr==='function')window.requestAnimationFrame=function(fn){return nr.call(this,trackScheduled(fn,'requestAnimationFrame'));};}catch(_){}
  try{if(window.scheduler&&typeof window.scheduler.postTask==='function'){const np=window.scheduler.postTask.bind(window.scheduler);window.scheduler.postTask=function(fn,options){return np(trackScheduled(fn,'scheduler.postTask'),options);};}}catch(_){}
  if(coldMode){try{const md=navigator.mediaDevices;if(md&&typeof md.getUserMedia==='function'){const ng=md.getUserMedia.bind(md);let carrier=null;md.getUserMedia=function(c){let audio=false,video=false;try{audio=!!(c&&c.audio);video=!!(c&&c.video);}catch(_){}if(audio&&!video){try{if(!carrier){const AC=window.AudioContext||window.webkitAudioContext,ac=AC?new AC({sampleRate:16000}):null;if(ac){const osc=ac.createOscillator(),gain=ac.createGain(),dest=ac.createMediaStreamDestination();osc.frequency.value=173;gain.gain.value=0;osc.connect(gain);gain.connect(dest);osc.start();carrier={stream:dest.stream,ac:ac,osc:osc,gain:gain};state.coldSyntheticCarrier=true;}}if(carrier)return Promise.resolve(carrier.stream);}catch(e){state.coldSyntheticErrors++;}}return ng(c);};}}catch(e){state.coldSyntheticErrors++;}}
  try{const X=window.XMLHttpRequest;if(X&&X.prototype&&!X.prototype.__aisR189Setup){const no=X.prototype.open,ns=X.prototype.send;X.prototype.open=function(method,url){try{this.__aisR189Url=String(url||'');}catch(_){}return no.apply(this,arguments);};X.prototype.send=function(body){try{const url=String(this.__aisR189Url||'');if(url.indexOf('/v1/bidiGenerateContent')>=0)state.bidiRequests++;const text=typeof body==='string'?body:'';if(url.indexOf('/v1/bidiGenerateContent')>=0&&text.toLowerCase().indexOf(TARGET_MODEL)>=0&&!/audio\/pcm/i.test(text)){state.setupObservations++;const c=currentContext;if(c)state.setupLinked++;else state.setupUnlinked++;if(!coldMode&&state.setupObservations===1){const chain=c?analyzeLineage(c):[];state.stage=c?'lineage-captured':'setup-unlinked';state.firstSetup={linked:!!c,context:contextMeta(c),lineage:chain.map(contextMeta),callbackCandidateCount:state.callbackCandidateCount,safeCallbackCandidateCount:state.safeCallbackCandidateCount,selected:state.selected,callbackTop:state.callbackTop};if(c)scheduleWarmReplay();}state.lastSetup={linked:!!c,context:contextMeta(c),setupObservation:state.setupObservations,coldMode:coldMode};}}catch(e){state.lastError=String(e&&e.name||'Error');}return ns.apply(this,arguments);};X.prototype.__aisR189Setup=true;}}catch(e){bridge('R189_HOOK_ERROR',{target:'XMLHttpRequest',name:String(e&&e.name||'Error')});}
  function configure(code){state.configured=true;state.targetLanguage=safeCode(code);return describe();}
  function reset(){if(coldMode)return describe();if(replayTimer!==null){try{nativeClearTimeout(replayTimer);}catch(_){}replayTimer=null;}if(replayEvalTimer!==null){try{nativeClearTimeout(replayEvalTimer);}catch(_){}replayEvalTimer=null;}try{sessionStorage.removeItem(FP_KEY);}catch(_){}state.stage='idle';state.listenerRoots=state.asyncScheduled=state.asyncRuns=state.contextDrops=state.bidiRequests=state.setupObservations=state.setupLinked=state.setupUnlinked=state.lineageDepth=0;state.callbackCandidateCount=state.safeCallbackCandidateCount=0;state.callbackTop=[];state.selected=null;state.callbackReplayAttempts=state.callbackReplayReturns=state.callbackReplayPromises=state.callbackReplayErrors=state.callbackReplaySetupSendDelta=state.callbackReplayBidiDelta=0;state.callbackReplayOutcome='not-run';state.persistedFingerprint=null;state.lastRoot=state.firstSetup=state.lastSetup=null;currentContext=null;nextContextId=1;contexts.length=0;contextById.clear();callbackCandidates.length=0;return describe();}
  function describe(){return Object.assign({ok:true,version:VERSION,targetModel:TARGET_MODEL,configured:state.configured,targetLanguage:state.targetLanguage,contextCount:contexts.length},state);}
  if(coldMode){try{const g=window.__AIS_R183_LANGUAGE__;if(g&&typeof g.configure==='function')g.configure('vi');}catch(_){}nativeSetTimeout(function(){if(state.coldReplayAttempts===0&&coldMatches.length===0){state.coldOutcome='cold-fingerprint-not-seen';state.stage='cold-fingerprint-not-seen';bridge('R189_COLD_FINGERPRINT_NOT_SEEN',{fingerprint:bootFingerprint,observed:state.coldCallbacksObserved});}},9000);}
  window.__AIS_R183B_BOOTSTRAP__={version:VERSION,configure:configure,reset:reset,describe:describe};
  bridge('R189_ENGINE_INSTALLED',{version:VERSION,mode:state.mode,warmOnly:state.warmOnly,coldFingerprint:bootFingerprint||null,coldBootstrapProven:false});
})();
""".trimIndent()
}
